# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0014c7004340dec075943320c5dafb26a44098955c8ff94a6923c41fd27cb67d857890b5802cd7c19a032c810c2a595a0e51e2955d4b837452e2b348910b1b23

test:
  secret_key_base: 8240ae8ef920615e9d733694d86a049ae246e7ebfb7493474c6a953f879acb2b48c61041924c74e5c199e88fb68266c353715a1330292224ff764ad0c0255e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
